---
project_name: kaytu

release:
  github:
    owner: "{{ .Env.REPOSITORY_OWNER }}"
    name:  "{{ .Env.REPOSITORY_NAME }}"
  prerelease: auto
  make_latest: "{{ .Env.GORELEASER_MAKE_LATEST}}"

checksum: {}

builds:
  - id: linux
    binary: kaytu
    ldflags:
      - -s -w -linkmode external -extldflags '-static' -X github.com/{{ .Env.REPOSITORY_OWNER }}/{{ .Env.REPOSITORY_NAME }}/pkg/version.VERSION={{ .Version }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CC=/usr/bin/musl-gcc
    main: ./main.go
  - id: darwin_amd64
    binary: kaytu
    ldflags:
      - -s -w -linkmode external -extldflags '-static' -X github.com/{{ .Env.REPOSITORY_OWNER }}/{{ .Env.REPOSITORY_NAME }}/pkg/version.VERSION={{ .Version }}
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=/usr/bin/musl-gcc
    main: ./main.go
  - id: darwin_arm64
    binary: kaytu
    ldflags:
      - -s -w -X github.com/{{ .Env.REPOSITORY_OWNER }}/{{ .Env.REPOSITORY_NAME }}/pkg/version.VERSION={{ .Version }}
    goos:
      - darwin
    goarch:
      - arm64
    main: ./main.go
  - id: windows
    binary: kaytu
    ldflags:
      - -s -w -linkmode external -extldflags '-static' -X github.com/{{ .Env.REPOSITORY_OWNER }}/{{ .Env.REPOSITORY_NAME }}/pkg/version.VERSION={{ .Version }}
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=/usr/bin/musl-gcc
    main: ./main.go
archives:
  - id: binary
    format: binary
  - id: windows
    format: zip
    builds: [windows]
  - id: linux
    format: tar.gz
    builds: [linux]
  - id: darwin 
    format: tar.gz
    builds: [darwin]


brews:
  - name: kaytu
    homepage: https://github.com/{{ .Env.REPOSITORY_OWNER }}/{{ .Env.REPOSITORY_NAME }}
    repository:
      owner: "{{ .Env.REPOSITORY_OWNER }}"
      name: "{{ .Env.HOMEBREW_TAP }}" 
    commit_author:
      name:  "{{ .Env.REPOSITORY_OWNER }}"
      email: "{{ .Env.OWNER_EMAIL }}"
    ids:
      - linux
      - darwin


#chocolateys:
#  - name: kaytu
#    ids:
#      - kaytu
#    package_source_url: https://github.com/kaytu-io/kaytu
#    owners: Kaytu Inc.
#    title: kaytu
#    authors: Kaytu
#    project_url: https://kaytu.io/
#    tags: "kaytu"
#    summary: Kaytu cli program
#    description: Kaytu cli program
#    dependencies:
#      - id: nfpm
#        version: 2.20.0
#    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#    source_repo: "https://push.chocolatey.org/"
#    skip_publish: false
#    goamd64: v1
#    files:
#      - src: "dist/windows_amd64/kaytu.exe"
#        dest: "bin"
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      - "sign-blob"
      - "--key=env://COSIGN_SECRET"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
